### ISSUE TITLE
Contextify Error (install node-gyp rebuild)

### ISSUE THREAD

**Issue by dlewis2017** [mapd/mapd-charting#117]
## :beetle:
  - [X] Operating System and version: MacOS Sierra 10.12.6 
  - [X] Browser and version: Chrome 61.0.3163.100
  - [X] Npm version: 5.5.1
  - [X] Node version: v8.2.1
  - [X] Steps to reproduce (including dashboard link): Clone repository and then run "npm install"
  - [X] Description of issue: (see below)

<h3>ISSUE DESCRIPTION</h3>
When attempting to build mapd-charting so I play around with it and attempt to build something, I get the errors seen below. Any advice on how to resolve this issue would be greatly appreciated.

<h3>Solutions I've tried:</h3>
Most of the comments from this link
https://github.com/nodejs/node-gyp/issues/809#issuecomment-155629365

<h3>LOGS</h3>

```
> contextify@0.1.15 install /Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/contextify
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8.h:3674:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8.h:3227:3: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8.h:3227:3: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8.h:3227:3: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/davidlewis/.node-gyp/8.2.1/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/contextify
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidlewis/.npm/_logs/2017-10-31T16_14_40_881Z-debug.log
```

**Comment by dlewis2017** [comment]
I downgraded to Node 6.9.2 and it compiled with no errors but still tons of warnings

**Comment by dlewis2017** [comment]
Now I'm receiving this error on "npm run start" (webpack failing to compile). Help with fixing either the first issue or this one would be great. It could have something with the fact that the main version of webpack needed is 3.3.0 but other npm modules require older versions of certain pieces of the webpack but I'm not sure.

Message received before when `UNMET PEER DEPENDENCY webpack3.3.0` was not met:
`npm WARN babel-loader@6.2.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN sass-loader@3.1.2 requires a peer of webpack@^1.12.6 but none was installed.`

```
> @mapd/mapdc@1.0.0 start /Users/davidlewis/Cyber/WebDashboard/mapd-charting
> webpack-dev-server --content-base ./example --config ./example/webpack.config.js "run"

Project is running at http://localhost:8080/
webpack output is served from /assets/
Content not from webpack is served from /Users/davidlewis/Cyber/WebDashboard/mapd-charting/example
Hash: ff0dde6ed4305fe6ba26
Version: webpack 3.3.0
Time: 14930ms
                              Asset     Size  Chunks                    Chunk Names
                  app.bundle.js.map  6.62 MB       0  [emitted]         app
                      app.bundle.js  5.14 MB       0  [emitted]  [big]  app
    multilayerscatterplot.bundle.js   339 kB       2  [emitted]  [big]  multilayerscatterplot
            multilayermap.bundle.js   337 kB       3  [emitted]  [big]  multilayermap
                 example3.bundle.js   324 kB       4  [emitted]  [big]  example3
                 example4.bundle.js   331 kB       5  [emitted]  [big]  example4
                     main.bundle.js   318 kB       6  [emitted]  [big]  main
                  geoheat.bundle.js   656 kB       1  [emitted]  [big]  geoheat
              geoheat.bundle.js.map   792 kB       1  [emitted]         geoheat
multilayerscatterplot.bundle.js.map   400 kB       2  [emitted]         multilayerscatterplot
        multilayermap.bundle.js.map   398 kB       3  [emitted]         multilayermap
             example3.bundle.js.map   385 kB       4  [emitted]         example3
             example4.bundle.js.map   392 kB       5  [emitted]         example4
                 main.bundle.js.map   376 kB       6  [emitted]         main
  [42] (webpack)-dev-server/client?http://localhost:8080 5.59 kB {0} {1} {2} {3} {4} {5} {6} [built]
 [247] multi (webpack)-dev-server/client?http://localhost:8080 script-loader!@mapd/connector/dist/browser-connector.js script-loader!@mapd/crossfilter/dist/mapd-crossfilter.js ./index.js 64 bytes {0} [built]
 [248] ./node_modules/script-loader!./node_modules/@mapd/connector/dist/browser-connector.js 307 bytes {0} [built]
 [250] ./node_modules/script-loader!./node_modules/@mapd/crossfilter/dist/mapd-crossfilter.js 308 bytes {0} [built]
 [252] ./index.js 58 bytes {0} [built]
 [302] multi (webpack)-dev-server/client?http://localhost:8080 ./example/example3.js 40 bytes {4} [built]
 [303] ./example/example3.js 272 bytes {4} [built]
 [305] multi (webpack)-dev-server/client?http://localhost:8080 ./example/example4.js 40 bytes {5} [built]
 [306] ./example/example4.js 13.3 kB {5} [built]
 [307] multi (webpack)-dev-server/client?http://localhost:8080 ./example/exampleMultiLayerMap.js 40 bytes {3} [built]
 [308] ./example/exampleMultiLayerMap.js 284 bytes {3} [built]
 [310] multi (webpack)-dev-server/client?http://localhost:8080 ./example/exampleMultiLayerScatterplot.js 40 bytes {2} [built]
 [311] ./example/exampleMultiLayerScatterplot.js 292 bytes {2} [built]
 [313] multi (webpack)-dev-server/client?http://localhost:8080 ./example/exampleGeoHeat.js 40 bytes {1} [built]
 [315] multi (webpack)-dev-server/client?http://localhost:8080 run 40 bytes {6} [built]
    + 301 hidden modules

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 run
Module not found: Error: Can't resolve 'run' in '/Users/davidlewis/Cyber/WebDashboard/mapd-charting'
 @ multi (webpack)-dev-server/client?http://localhost:8080 run

ERROR in ./node_modules/css-loader!./node_modules/sass-loader!./scss/chart.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/davidlewis/Cyber/WebDashboard/mapd-charting/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./scss/chart.scss 4:14-112
 @ ./node_modules/babel-loader!./src/index.js
 @ ./node_modules/expose-loader?dc!./src/index.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 script-loader!@mapd/connector/dist/browser-connector.js script-loader!@mapd/crossfilter/dist/mapd-crossfilter.js ./index.js
webpack: Failed to compile.
```

**Comment by dlewis2017** [comment]
<h1>RESOLVED</h1>
Downgraded to Node 6.9.2
`npm install`
`npm install mapbox-gl@https://github.com/mapd/mapbox-gl-js/tarball/9c04de6949fe498c8c79f5c0627dfd6d6321f307 #downloads mapbox peer dependency`
`npm install -g webpack@3.8.1`
`npm start run`

**Comment by micahstubbs** [comment]
facing this error as well, when I attempt to `yarn install`

node `v9.0.0`
yarn `1.3.21`

**Comment by brunofin** [comment]
As well facing this error:

node 9.2.0
yarn 1.3.2

**Comment by micahstubbs** [comment]
I've found a workaround:

```
yarn install
# when the error happens
ctrl + c
npm rebuild node-sass
```

 there's a long thread about this issue here.  basically, `node-sass` isn't really maintained and has many problems.  a long term solution is probably to migrate away from `node-sass`
https://github.com/sass/node-sass/issues/1918
